version: "3"
services:
  api:
    build:
      context: api
    environment:
      - API_PORT=8080
      - API_ALLOWED_ORIGINS=http://datasim.tla.adlnet.gov
#      - API_ALLOWED_ORIGINS=http://10.5.0.5
      - CREDENTIALS=user:pass
    ports:
      - "8080:8080"
    networks:
      - public
 #       ipv4_address: 10.5.0.6
      
  nginx:
    build:
      context: nginx
    environment:
      - HOSTNAME=localhost
    ports:
      - "80:80"
    networks:
      - public
#        ipv4_address: 10.5.0.5

networks:
  public: 
    driver: bridge
#    ipam:
#     config:
#       - subnet: 10.5.0.0/16
#         gateway: 10.5.0.1
